version: '3.7'

services:

  styles:
    build:
      context: ./styles
      dockerfile: Dockerfile
    volumes:
      - type: bind
        source: ./styles/src
        target: /src
      - type: bind
        source: ./site
        target: /src/site
      - /src/node_modules
    working_dir: /src
    command: gulp

  jekyll:
    build:
      context: .
      dockerfile: Dockerfile
      target: development
    volumes:
      - type: bind
        source: .
        target: /src
      - /src/node_modules
      - /usr/local/bundle
    depends_on:
      - styles      
    ports:
      - '3000:3000'
      - '35729:35729'
    working_dir: /src
    command: |
      bundle exec jekyll serve \
        --drafts \
        --future \
        --livereload \
        --port 3000 \
        --trace \
        --unpublished \
        --host 0.0.0.0
