version: 0.2

env:
  variables:
    DOCKER_BUILDKIT: "1"

phases:
  install:
    commands:
      - $(aws ecr get-login --no-include-email)

  pre_build:
    commands:
      - docker pull "${REPOSITORY_URI}:latest" || true

  build:
    commands:
      - |
        docker build \
          --build-arg BUILDKIT_INLINE_CACHE=1 \
          --cache-from "${REPOSITORY_URI}:latest" \
          --tag "${REPOSITORY_URI}:latest" \
          --target build \
          .
      - |
        docker build \
          --cache-from "${REPOSITORY_URI}:latest" \
          -o dist \
          .
  post_build:
    commands:
      - docker push "${REPOSITORY_URI}:latest"

artifacts:
  type: zip
  base-directory: dist
  files:
    - './**/*'
