AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Parameters:
  StackName:
    Type: String
  
  ServiceRole:
    Type: String

Resources:

  ViewerRequestLambdaFunction:
      Type: AWS::Serverless::Function
      Properties:
        CodeUri: ../../lambda/src
        Role: !GetAtt LambdaEdgeFunctionRole.Arn
        Runtime: nodejs12.x
        Handler: index.handler
        AutoPublishAlias: live

  WebBucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: Private
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  Cloudfront:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Comment: !Sub "${StackName} CDN"
        Enabled: true
        HttpVersion: http2
        DefaultRootObject: index.html
        CustomErrorResponses:
          - ErrorCode: 404
            ResponseCode: 404
            ResponsePagePath: /error.html
        Origins:
          - Id: website
            CustomOriginConfig: 
              OriginProtocolPolicy: http-only
            DomainName: !Select
              - 2
              - !Split
                - "/"
                - !Sub ${WebBucket.WebsiteURL}
        
        DefaultCacheBehavior:
          TargetOriginId: website
          ViewerProtocolPolicy: redirect-to-https
          ForwardedValues:
            QueryString: false
            Headers:
              - Origin
          LambdaFunctionAssociations:
            - EventType: viewer-request
              LambdaFunctionARN: !Ref ViewerRequestLambdaFunction.Version

  ResourceAccessPolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: ResourceAccessPolicy
      Roles:
        - !Ref ServiceRole
      PolicyDocument:
        Statement:
          - Resource:
              - !Sub ${WebBucket.Arn}
              - !Sub ${WebBucket.Arn}/*
            Effect: Allow
            Action:
              - s3:DeleteObject
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:ListBucket
              - s3:PutObject
              - s3:PutObjectACL
          - Resource:
              - !Sub arn:aws:cloudfront::${AWS::AccountId}:distribution/${Cloudfront}
            Effect: Allow
            Action:
              - cloudfront:CreateInvalidation

  LambdaEdgeFunctionRole:
    Type: AWS::IAM::Role
    Properties:
        Path: "/"
        ManagedPolicyArns:
            - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        AssumeRolePolicyDocument:
          Version: "2012-10-17"
          Statement:
            - Sid: "AllowLambdaServiceToAssumeRole"
              Effect: "Allow"
              Action: 
                - "sts:AssumeRole"
              Principal:
                Service: 
                  - "lambda.amazonaws.com"
                  - "edgelambda.amazonaws.com"

Outputs:

  Url:
    Value: !Sub "https://${Cloudfront.DomainName}"

  DistributionId:
    Value: !Ref Cloudfront

  Bucket:
    Value: !Sub "s3://${WebBucket}"
